// SPDX-License-Identifier: LGPL-3.0-or-later
import { Errno } from 'kerium';

/**
 * ZenFS and Emscripten do not number their errnos the same way, and this is the translation between them.
 */
const linuxToEmscripten: Record<number, number> = {
	[Errno.EPERM]: 63,
	[Errno.ENOENT]: 44,
	[Errno.ESRCH]: 71,
	[Errno.EINTR]: 27,
	[Errno.EIO]: 29,
	[Errno.ENXIO]: 60,
	[Errno.E2BIG]: 1,
	[Errno.ENOEXEC]: 45,
	[Errno.EBADF]: 8,
	[Errno.ECHILD]: 12,
	[Errno.EAGAIN]: 6,
	[Errno.ENOMEM]: 48,
	[Errno.EACCES]: 2,
	[Errno.EFAULT]: 21,
	[Errno.ENOTBLK]: 105,
	[Errno.EBUSY]: 10,
	[Errno.EEXIST]: 20,
	[Errno.EXDEV]: 75,
	[Errno.ENODEV]: 43,
	[Errno.ENOTDIR]: 54,
	[Errno.EISDIR]: 31,
	[Errno.EINVAL]: 28,
	[Errno.ENFILE]: 41,
	[Errno.ENOTTY]: 59,
	[Errno.EMFILE]: 33,
	[Errno.ETXTBSY]: 74,
	[Errno.EFBIG]: 22,
	[Errno.ENOSPC]: 51,
	[Errno.ESPIPE]: 70,
	[Errno.EROFS]: 69,
	[Errno.EMLINK]: 34,
	[Errno.EPIPE]: 64,
	[Errno.EDOM]: 18,
	[Errno.ERANGE]: 68,
	[Errno.EDEADLK]: 16,
	[Errno.ENAMETOOLONG]: 37,
	[Errno.ENOLCK]: 46,
	[Errno.ENOSYS]: 52,
	[Errno.ENOTEMPTY]: 55,
	[Errno.ELOOP]: 32,
	[Errno.ENOMSG]: 49,
	[Errno.EIDRM]: 24,
	[Errno.ECHRNG]: 106,
	[Errno.EL2NSYNC]: 156,
	[Errno.EL3HLT]: 107,
	[Errno.EL3RST]: 108,
	[Errno.ENRNG]: 109, // ELNRNG on Linux
	[Errno.EUNATCH]: 110,
	[Errno.ECSI]: 111, // ENOCSI on Linux
	[Errno.EL2HLT]: 112,
	[Errno.EBADE]: 113,
	[Errno.EBADR]: 114,
	[Errno.EXFULL]: 115,
	[Errno.ENOANO]: 104,
	[Errno.EBADRQC]: 103,
	[Errno.EBADSLT]: 102,
	[Errno.EBFONT]: 101,
	[Errno.ENOSTR]: 100,
	[Errno.ENODATA]: 116,
	[Errno.ETIME]: 117,
	[Errno.ENOSR]: 118,
	[Errno.ENONET]: 119,
	[Errno.ENOPKG]: 120,
	[Errno.EREMOTE]: 121,
	[Errno.ENOLINK]: 47,
	[Errno.EADV]: 122,
	[Errno.ESRMNT]: 123,
	[Errno.ECOMM]: 124,
	[Errno.EPROTO]: 65,
	[Errno.EMULTIHOP]: 36,
	[Errno.EDOTDOT]: 125,
	[Errno.EBADMSG]: 9,
	[Errno.EOVERFLOW]: 61,
	[Errno.ENOTUNIQ]: 126,
	[Errno.EBADFD]: 127,
	[Errno.EREMCHG]: 128,
	[Errno.ELIBACC]: 129,
	[Errno.ELIBBAD]: 130,
	[Errno.ELIBSCN]: 131,
	[Errno.ELIBMAX]: 132,
	[Errno.ELIBEXEC]: 133,
	[Errno.EILSEQ]: 25,
	[Errno.ERESTART]: 134,
	[Errno.ESTRPIPE]: 135,
	[Errno.EUSERS]: 136,
	[Errno.ENOTSOCK]: 57,
	[Errno.EDESTADDRREQ]: 17,
	[Errno.EMSGSIZE]: 35,
	[Errno.EPROTOTYPE]: 67,
	[Errno.ENOPROTOOPT]: 50,
	[Errno.EPROTONOSUPPORT]: 66,
	[Errno.ESOCKTNOSUPPORT]: 137,
	[Errno.ENOTSUP]: 138,
	[Errno.EPFNOSUPPORT]: 139,
	[Errno.EAFNOSUPPORT]: 5,
	[Errno.EADDRINUSE]: 3,
	[Errno.EADDRNOTAVAIL]: 4,
	[Errno.ENETDOWN]: 38,
	[Errno.ENETUNREACH]: 40,
	[Errno.ENETRESET]: 39,
	[Errno.ECONNABORTED]: 13,
	[Errno.ECONNRESET]: 15,
	[Errno.ENOBUFS]: 42,
	[Errno.EISCONN]: 30,
	[Errno.ENOTCONN]: 53,
	[Errno.ESHUTDOWN]: 140,
	[Errno.ETOOMANYREFS]: 141,
	[Errno.ETIMEDOUT]: 73,
	[Errno.ECONNREFUSED]: 14,
	[Errno.EHOSTDOWN]: 142,
	[Errno.EHOSTUNREACH]: 23,
	[Errno.EALREADY]: 7,
	[Errno.EINPROGRESS]: 26,
	[Errno.ESTALE]: 72,
	[Errno.EEUCLEAN]: 143, // EUCLEAN on Linux
	[Errno.ENOTNAM]: 144,
	[Errno.ENAVAIL]: 145,
	[Errno.EISNAM]: 146,
	[Errno.EREMOTEIO]: 147,
	[Errno.EDQUOT]: 19,
	[Errno.ENOMEDIUM]: 148,
	[Errno.EMEDIUMTYPE]: 149,
	[Errno.ECANCELED]: 11,
	[Errno.ENOKEY]: 150,
	[Errno.EKEYEXPIRED]: 151,
	[Errno.EKEYREVOKED]: 152,
	[Errno.EKEYREJECTED]: 153,
	[Errno.EOWNERDEAD]: 62,
	[Errno.ENOTRECOVERABLE]: 56,
	[Errno.ERFKILL]: 154,
	[Errno.EHWPOISON]: 155,
} satisfies Record<Errno, number>;

/**
 * A Linux errno as Emscripten numbers it. Values outside kerium's `Errno` are passed through.
 */
export function toEmscriptenErrno(errno: number): number {
	return linuxToEmscripten[errno] ?? errno;
}
