name: Release
on:
    release:
        types: [created]
jobs:
    ci:
        name: CI
        uses: ./.github/workflows/ci.yaml
    docs:
        name: Docs
        uses: zen-fs/core/.github/workflows/deploy-docs.yaml@main
        needs: ci
    release:
        name: Release
        uses: zen-fs/core/.github/workflows/release-common.yaml@main
        needs: ci
        secrets: inherit
